# Generated by Django 2.2.2 on 2019-06-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='archivo',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='ultima_carga',
            field=models.DateField(auto_now_add=True),
        ),
    ]
