# Generated by Django 2.2.2 on 2019-06-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_remove_arquitecto_inmobiliarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquitecto',
            name='inmobiliaria',
            field=models.CharField(default='', max_length=30),
        ),
    ]
